title:
  en: ApplySquare
  zh: 申请方
subtitle:
  en: "ApplySquare."
  zh: "你好, 我是申请方."
keywords: "ApplySquare,申请方"
author:
  name: ApplySquare
  email: hello@applysquare.com
timezone: UTC
encoding: utf-8

url: http://blog.applysquare.com
repository: https://github.com/applysquare/applysquare.github.io
feed:
  en: http://blog.applysquare.com/feed.xml
  zh: http://blog.applysquare.com/订阅.xml
static_url: http://blog.applysquare.com/static
media_url: http://blog.applysquare.com/media
www_url: https://www.applysquare.com

debug: false
analytics: UA-41044126-5

lsi: false
safe: true
highlighter: rouge
permalink: /:year/:month/:title/
relative_permalinks: false
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - Rakefile
  - README.md
  - LICENSE

prose:
  media: "image"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Add Categories"
          options:
            - name: "ApplySquare"
              value: "applysquare"
            - name: "News"
              value: "news"
            - name: "Branding"
              value: "branding"
